# Spring Configuration
spring:
  application:
    name: welcome-call-service
  # Write dates as strings
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  # Database & JPA Settings
  datasource:
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.name:welcome_service}
    username: ${database.username:welcome_service_user}
    password: ${database.password:welcome_service_password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

# RabbitMQ properties
rabbitmq:
  queue: policy-issued
  topic-exchange: policy-issued-exchange
  routing-key: insurance.policies.#

# Web Server configuration
server:
  port: 19000
  # Requests to endpoints need to start with /welcomeservice/api
  servlet:
    context-path: /welcomeservice/api

# Logging related configuration
logging:
  file:
    path: './logs/${spring.application.name}'
    name: ${logging.file.path}/welcome-call-service.log.%d{yyyy-MM-dd_HH}
  level:
    root: info
    # Enable logging for transaction commit and rollback
    org.springframework.transaction.support: debug
  # Enable request logging
  request:
    log-request: true
    log-response: true
    pretty-print: false

# Swagger Documentation configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packagesToScan: org.insurance.welcomeservice.controller
  pathsToMatch: /v1/welcomecalls/**